package mx.org.dao.db.enums;

/**
 * Created by CARLOS.BARROSO on 09/04/2018.
 */

public enum EAccion {
    AGREGAR,
    MODIFICAR,
    TADETALLE,
    CONSULTAR,
    RESPALDAR_USB,
    RESTAURAR_USB,
    RESPALDO_AUTOMATICO_DD,
    RESPALDO_AUTOMATICO_USB,
    TRANSFERENCIA_USB,
    TRANSFERENCIA_WIFI,
    ELIMINAR,
    DEPURAR,
    COMPLEMENTAR ,
    FINALIZAR,
    VERIFICAR,
    BITACORA,
    GENERICO,
    DUPLICAR,
    //---ENVIOS
    GENERA,
    DEPOSITA,
    INTEGRA,
	REGENERA,
    //---SENTENCIAS-BITACORA
    DELETE_SENT_ENVIADAS,
    //---DATA BASE
    EJECUTA_VACUUM,
    VISITA_MANUAL,
    VISITA_CERRAR,
    //---NO RESPUESTA
    REGRESAR,
    LIBERAR,
    LIBERAR_CON_CAMBIO,
    FOTO,
    COMPLEMENTO,
    //-
    REGISTRAR,
    DESCARGAR,
    DESACTIVAR,
    LISTAR,
    JUSTIFICAR,
    COPIAR,
    SUBIR,
    BAJAR,
    ASIGNAR,
    ACTIVAR,
    PROCESAR,
    COMPLETO,
    CALCULAR,
    GENERAR,
    REPROCESAR,
    MOVIMIENTOS,
    NO_APLICA,
    ELIMINAR_CAPTURA,
    ELIMINAR_VERIFICACION,
    TRANSFORMACION,
    RECHAZAR,
    AMPLIAR,
    RESTAURAR;
}
